FEATURE_SIZE = 30

CLASSES = [
    "AIMchat",
    "aim_chat",
    "email",
    "facebook_audio",
    "facebookchat",
    "facebook_chat",
    "facebook_video",
    "ftps_down",
    "ftps_up",
    "gmailchat",
    "hangout_chat",
    "hangouts_audio",
    "hangouts_chat",
    "hangouts_video",
    "ICQchat",
    "icq_chat",
    "netflix",
    "scp",
    "scpDown",
    "scpUp",
    "sftp",
    "sftpDown",
    "sftp_down",
    "sftpUp",
    "sftp_up",
    "skype_audio",
    "skype_chat",
    "skype_file",
    "skype_video",
    "spotify",
    "torFacebook",
    "torGoogle",
    "Torrent",
    "torTwitter",
    "torVimeo",
    "torYoutube",
    "vimeo",
    "voipbuster",
    "vpn_aim_chat",
    "vpn_bittorrent",
    "vpn_email",
    "vpn_facebook_audio",
    "vpn_facebook_chat",
    "vpn_ftps",
    "vpn_hangouts_audio",
    "vpn_hangouts_chat",
    "vpn_icq_chat",
    "vpn_netflix",
    "vpn_sftp",
    "vpn_skype_audio",
    "vpn_skype_chat",
    "vpn_skype_files",
    "vpn_spotify",
    "vpn_vimeo",
    "vpn_voipbuster",
    "vpn_youtube",
    "youtube",
    "youtubeHTML",
]


PARTITIONS = 1024
